// TAD §D.5.13 — About copy carried verbatim from
// Coordinator_Copy_About_Panel_21AUG26.docx. Content, not architecture:
// edit at source and re-copy here rather than paraphrasing in place.
export const ABOUT_HEADING = 'About this application';

export const ABOUT_PARAGRAPHS: readonly string[] = [
  'This is a demonstration version of the FCC Program Integrator. It has one live piece of functionality, customer risk, to show the value of being able to navigate through layers of risk and control management to identify and resolve emerging risk areas in real time, rather than waiting for trends to emerge through periodic metrics or the annual risk assessment. The customers in this example are entirely synthetic, and the customer population is scaled well below what a bank like this would reasonably have, but all elements of the risk analysis are supported by realistic inputs including a documented customer risk rating methodology and scorecard, industry risk classification table, and geographical risk ratings derived from the 2025 Basel AML Index Public Edition. The rest of the dashboard, currently under development, shows illustrative values and ratings for the risks and controls of an FCC program at a fictional US regional bank. Once all modules are fully developed and integrated, the same drill-down capabilities will be available for all risk areas and controls.',
  'The FCC Program Integrator is designed as a configurable, modular platform, with each program component based on major market regulatory expectations and industry standards. The platform will allow any organization to take the FCC program it has, integrate all program components into a centralized dashboard, improve alignment between components, and use the consolidated view to prioritize the management of risks and control processes on a daily basis.',
  'The platform is currently under development by Chris Andre using an industry-standard development pipeline (React-on-Vercel) and a disciplined Claude project team. The application is currently being designed for desktop display, with mobile use scoped for future platform development.',
];
